### ISSUE TITLE
Setting the endpoint parameter breaks the extension.

### ISSUE THREAD

**Issue by lukolszewski** [JacksonKearl/ai-book#4]
If the endpoint parameter is set to anything including OpenAI's current endpoint" https://api.openai.com/v1/chat/completions" The extension fails to work. It doesn't even attempt to talk to the address provided, just errors with:

```
Error: Error accessing OpenAI. The "Update OpenAPI Api Key" command may help you.
undefined
	at [/home/luk/.vscode/extensions/jaaxxx.llm-book-0.1.1/dist/extension.js:1:4704](https://file+.vscode-resource.vscode-cdn.net/home/luk/.vscode/extensions/jaaxxx.llm-book-0.1.1/dist/extension.js:1:4704)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.<anonymous> (/home/luk/.vscode/extensions/jaaxxx.llm-book-0.1.1/dist/extension.js:1:2494)
	at async n.$executeCells (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:96089)
```

I know this is not an API key issue as when I delete the endpoint it works fine. This also prevents use of any local OpenAI api endpoints.

I don't know why would it fail as the code seems to set the endpoint to the same value, but it fails nevertheless.Screenshot attached.
![Screenshot from 2024-01-02 15-54-11](https://github.com/JacksonKearl/ai-book/assets/43611481/e54e3dc8-09b0-4639-b1ad-5517ed399b39)

**Comment by JacksonKearl** [comment]
The `Configure LLM` menu is for adjusting the fields included in the body of the request. I see the PR you raised.. including a `settings` field in the top-level .llm.json format is a possibility.

**Comment by JacksonKearl** [comment]
Pushed a new version which fixes the error message not being properly preserved.
